quarkus:
    http:
        port: 8080

# Configuración del pool de conexiones reactivo
    datasource:
        db-kind: postgresql
        reactive:
            url: http://postgresql://localhost:5432/quarkus_db
            max-size: 20
        username: admin
        password: secret

    # Habilitar Hibernate Reactive
    hibernate-orm:
        database:
            generation: drop-and-create
        log:
            sql: true